### PR TITLE
add Dutch translation

### PR DESCRIPTION
**Pull request by cascer1**

### CODE REVIEW

**Comment by rtorr** [comment]
@cascer1 awesome!

**Comment by cascer1** [comment]
Is it possible to translate those tags that get put in front of the explanations too? For example, 

here 

There I would translate it to [:tabnew] bestandsnaam of [:tabn] bestandsnaam

**Comment by rtorr** [comment]
Not currently no. Its possible to ad variables for that though

**Comment by cascer1** [comment]
That would be cool, makes it easier to write understandable explanations in some cases :)

**Pull request merged**
