### PR TITLE
Add f, t, paragraph motions and very-magic

### PR DESCRIPTION
**Pull request by matatk**
It's taken me a while, but here's the PR I mentioned I would make as per issue #81 - please let me know what you think.  I really like the build system for this project, and the way the languages are handled.  I'm not a language expert, so I have not been able to do the translations, though (which is why I'm not including the comment in here to auto-close that issue, as it's not really closed until the translations are done.)

### CODE REVIEW

**Comment by rtorr** [comment]
Awesome!

**Comment by rtorr** [comment]
merged https://github.com/rtorr/vim-cheat-sheet/pull/97

We can close it out. Its nice that it at least keeps the english versions in there.

**Comment by rtorr** [comment]
@matatk I will leave it up to you to leave it open or not, but I am ok with closing it without the new translations.

**Comment by matatk** [comment]
Glad you found the PRs helpful.  How about changing the title of #81 to say that the translations are needed, swap the two existing labels for 'bug' (or something else you think might be appropriate) and leave it open, so that the need for the translations is remembered?

(I can change the issue title and am happy to, but I'm not able to change the labels.)

**Pull request merged**
